// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxf-LOKpSU3WyiCjCriyXR0C5pof_8Qw',
    appId: '1:803593642779:web:bf68d9767afe4704a8e9be',
    messagingSenderId: '803593642779',
    projectId: 'scrintelligent',
    authDomain: 'scrintelligent.firebaseapp.com',
    storageBucket: 'scrintelligent.firebasestorage.app',
    measurementId: 'G-JRFPZQSGJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB967BwO4T1n5sB9hT7B6fkfOktnMT11Cs',
    appId: '1:803593642779:android:bf07b6b6af7252bba8e9be',
    messagingSenderId: '803593642779',
    projectId: 'scrintelligent',
    storageBucket: 'scrintelligent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaSgAAzoKxDbGzb84i3NkdJXBgav17Rvk',
    appId: '1:803593642779:ios:3ffdacbfcdaecb37a8e9be',
    messagingSenderId: '803593642779',
    projectId: 'scrintelligent',
    storageBucket: 'scrintelligent.firebasestorage.app',
    iosBundleId: 'com.example.scrintelligent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaSgAAzoKxDbGzb84i3NkdJXBgav17Rvk',
    appId: '1:803593642779:ios:3ffdacbfcdaecb37a8e9be',
    messagingSenderId: '803593642779',
    projectId: 'scrintelligent',
    storageBucket: 'scrintelligent.firebasestorage.app',
    iosBundleId: 'com.example.scrintelligent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZxf-LOKpSU3WyiCjCriyXR0C5pof_8Qw',
    appId: '1:803593642779:web:799dcc88b577d609a8e9be',
    messagingSenderId: '803593642779',
    projectId: 'scrintelligent',
    authDomain: 'scrintelligent.firebaseapp.com',
    storageBucket: 'scrintelligent.firebasestorage.app',
    measurementId: 'G-3BG6H9SHTV',
  );
}
